FROM node:20-slim AS base
ENV NODE_OPTIONS="--dns-result-order=ipv4first"
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS builder
WORKDIR /app
COPY . .
# Menggunakan pnpm lockfile
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Mem-build aplikasi business
RUN pnpm --filter @adatrack/business run build

FROM base AS runner
WORKDIR /app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

# Copy hasil build standalone
COPY --from=builder --chown=nextjs:nodejs /app/apps/business/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/business/.next/static ./apps/business/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/business/public ./apps/business/public

CMD node apps/business/server.js
