FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apk add --no-cache libc6-compat

FROM base AS builder
WORKDIR /app
COPY . .
# Menggunakan pnpm lockfile
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Mem-build aplikasi personal
RUN pnpm --filter @adatrack/personal run build

FROM base AS runner
WORKDIR /app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

# Copy hasil build standalone
COPY --from=builder --chown=nextjs:nodejs /app/apps/personal/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/personal/.next/static ./apps/personal/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/personal/public ./apps/personal/public

CMD node apps/personal/server.js
