import * as fs from 'fs';

const filePath = 'd:/03. DEVELOPMENT/03. AJB/GPS/binago/apps/business/src/i18n/index.ts';
let content = fs.readFileSync(filePath, 'utf8');

// Add to id.navGroup
content = content.replace(/(\s*administration:\s*'Administrasi',)/, "$1\n      rental: 'Rental',\n      transport: 'Transport',\n      logistics: 'Logistics',\n      sales: 'Sales',\n      fieldService: 'Field Service',\n      patrol: 'Patrol',\n      projectSite: 'Project / Site',");

// Add to en.navGroup
content = content.replace(/(\s*administration:\s*'Administration',)/, "$1\n      rental: 'Rental',\n      transport: 'Transport',\n      logistics: 'Logistics',\n      sales: 'Sales',\n      fieldService: 'Field Service',\n      patrol: 'Patrol',\n      projectSite: 'Project / Site',");

// Add to id.nav
content = content.replace(/(\s*alerts:\s*'Peringatan',)/, "$1\n\n      // Rental\n      dashboardRental: 'Dashboard Rental',\n      customers: 'Pelanggan',\n      rentalContracts: 'Kontrak Rental',\n      reservations: 'Reservasi',\n      handovers: 'Serah Terima',\n      returns: 'Pengembalian',\n      rentalReports: 'Laporan Rental',\n\n      // Transport\n      dashboardTransport: 'Dashboard Transport',\n      operationalSchedules: 'Jadwal Operasional',\n      routesTransport: 'Trayek',\n      stops: 'Halte',\n      departures: 'Keberangkatan',\n      passengerManifests: 'Manifest Penumpang',\n      transportReports: 'Laporan Transport',\n\n      // Logistics\n      dashboardLogistics: 'Dashboard Logistics',\n      logisticsCustomers: 'Customer',\n      shippingOrders: 'Order Pengiriman',\n      shipments: 'Pengiriman',\n      manifests: 'Manifest',\n      deliveriesLogistics: 'Delivery',\n      proofOfDelivery: 'Proof of Delivery',\n      logisticsReports: 'Laporan Logistics',\n\n      // Sales\n      dashboardSales: 'Dashboard Sales',\n      salesCustomers: 'Customer',\n      salesVisits: 'Sales Visit',\n      prospects: 'Prospek',\n      quotes: 'Penawaran',\n      orders: 'Order',\n      salesReports: 'Laporan Sales',\n\n      // Field Service\n      dashboardFieldService: 'Dashboard Field Service',\n      fieldServiceCustomers: 'Customer',\n      workOrders: 'Work Order',\n      assignments: 'Penugasan',\n      schedules: 'Jadwal',\n      technicians: 'Teknisi',\n      completions: 'Penyelesaian',\n      fieldServiceReports: 'Laporan Field Service',\n\n      // Patrol\n      dashboardPatrol: 'Dashboard Patrol',\n      patrolSchedules: 'Jadwal Patrol',\n      patrolAssignments: 'Penugasan',\n      checkpoints: 'Checkpoint',\n      inspections: 'Inspeksi',\n      patrolIncidents: 'Insiden',\n      patrolReports: 'Laporan Patrol',\n      patrolHistory: 'Riwayat Patrol',\n\n      // Project / Site\n      dashboardProject: 'Dashboard Project',\n      projects: 'Project',\n      sites: 'Site',\n      projectAssignments: 'Penugasan',\n      projectSchedules: 'Jadwal',\n      projectActivities: 'Aktivitas',\n      projectIncidents: 'Insiden',\n      projectReports: 'Laporan Project',");

// Add to en.nav
content = content.replace(/(\s*alerts:\s*'Alerts',)/, "$1\n\n      // Rental\n      dashboardRental: 'Rental Dashboard',\n      customers: 'Customers',\n      rentalContracts: 'Rental Contracts',\n      reservations: 'Reservations',\n      handovers: 'Handovers',\n      returns: 'Returns',\n      rentalReports: 'Rental Reports',\n\n      // Transport\n      dashboardTransport: 'Transport Dashboard',\n      operationalSchedules: 'Operational Schedules',\n      routesTransport: 'Routes',\n      stops: 'Stops',\n      departures: 'Departures',\n      passengerManifests: 'Passenger Manifests',\n      transportReports: 'Transport Reports',\n\n      // Logistics\n      dashboardLogistics: 'Logistics Dashboard',\n      logisticsCustomers: 'Customers',\n      shippingOrders: 'Shipping Orders',\n      shipments: 'Shipments',\n      manifests: 'Manifests',\n      deliveriesLogistics: 'Deliveries',\n      proofOfDelivery: 'Proof of Delivery',\n      logisticsReports: 'Logistics Reports',\n\n      // Sales\n      dashboardSales: 'Sales Dashboard',\n      salesCustomers: 'Customers',\n      salesVisits: 'Sales Visits',\n      prospects: 'Prospects',\n      quotes: 'Quotes',\n      orders: 'Orders',\n      salesReports: 'Sales Reports',\n\n      // Field Service\n      dashboardFieldService: 'Field Service Dashboard',\n      fieldServiceCustomers: 'Customers',\n      workOrders: 'Work Orders',\n      assignments: 'Assignments',\n      schedules: 'Schedules',\n      technicians: 'Technicians',\n      completions: 'Completions',\n      fieldServiceReports: 'Field Service Reports',\n\n      // Patrol\n      dashboardPatrol: 'Patrol Dashboard',\n      patrolSchedules: 'Patrol Schedules',\n      patrolAssignments: 'Assignments',\n      checkpoints: 'Checkpoints',\n      inspections: 'Inspections',\n      patrolIncidents: 'Incidents',\n      patrolReports: 'Patrol Reports',\n      patrolHistory: 'Patrol History',\n\n      // Project / Site\n      dashboardProject: 'Project Dashboard',\n      projects: 'Projects',\n      sites: 'Sites',\n      projectAssignments: 'Assignments',\n      projectSchedules: 'Schedules',\n      projectActivities: 'Activities',\n      projectIncidents: 'Incidents',\n      projectReports: 'Project Reports',");

fs.writeFileSync(filePath, content, 'utf8');
console.log('Translations updated!');
